postinst: fix error handling if actions fails and adjust code indention

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -7,9 +7,11 @@ then
 	then
 		echo "Ok"
 	else
-		echo "Failed"
+		echo "Failed" >&2
+		exit 1
 	fi
 fi
 
- #DEBHELPER#
- exit 0
+#DEBHELPER#
+
+exit 0
